#!/usr/bin/python
# Copyright (c) Members of the EGEE Collaboration. 2004. 
# See http://www.eu-egee.org/partners/ for details on the copyright
# holders.  
#
# Licensed under the Apache License, Version 2.0 (the "License"); 
# you may not use this file except in compliance with the License. 
# You may obtain a copy of the License at 
#
#     http://www.apache.org/licenses/LICENSE-2.0 
#
# Unless required by applicable law or agreed to in writing, software 
# distributed under the License is distributed on an "AS IS" BASIS, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
# See the License for the specific language governing permissions and 
# limitations under the License.

import sys

from GLUEInfoProvider import CommonUtils
from GLUEInfoProvider import ShSiteDefHandler
from GLUEInfoProvider import GLUECEHandler
from GLUEInfoProvider import GLUEClusterHandler

def main():
    
    try:
        if len(sys.argv) <> 2:
            raise Exception("Usage: info-provider-glue <config-file>")
            
        config = CommonUtils.readConfigFile(sys.argv[1])

        siteDefs = ShSiteDefHandler.parse(config)

        GLUECEHandler.process(siteDefs)
        
        GLUEClusterHandler.process(siteDefs)
        
    except Exception, ex:
        etype, evalue, etraceback = sys.exc_info()
        sys.excepthook(etype, evalue, etraceback)
        sys.exit(1)


if __name__ == "__main__":
    main()

